### ISSUE TITLE
no hook result when internal service call

### ISSUE THREAD

**Issue by ryuken** [feathersjs/feathers-hooks#106]
Hi I have service A and service B.
Service B calls service A via app.services.
Service A has a after hook on GET, which does get executed.
The problem is that the result I get isn't the result from the after hook, but when you normally do a fetch with mongoose.

Is this a bug?

**Comment by marshallswain** [comment]
@ryuken, can you post some code?  Are you expecting service A's after hook to change the result you get from service B?  If so, you'll need to use the response you get inside the after hook to overwrite `hook.result`.  But I'm not sure I understand your expectations.

**Comment by ryuken** [comment]
Nah I'm calling service A inside service B. The after hook of service A does run but I don't get that result from the call inside service B. I need the changed data from the after hook inside service B. I'll post some code later.

**Comment by ryuken** [comment]
Service A is just a mongoose service which get's data from the database.
The get after hook just add's some data to the hook.result

Service B is a custom service generated by feathers generate service (without db)

```
class Service {
	constructor(options) {
		this.options = options || {};
	}
        patch(id, data, params) {
              const gameSessionService = this.options.app.services.game_sessions
              gameSessionService.get(id).then(g => {
                    console.log(g); // <-- doesn't contain the get after hook data, but just the data from the mongoose call
               })


app.use('/service', new Service({ app : app })); // <-- i pass app like this
```

**Comment by daffl** [comment]
I can't reproduce the problem you are describing. With a setup like:

```js
'use strict';

const feathers = require('feathers');
const hooks = require('feathers-hooks');

class ServiceA {
  constructor(options) {
    this.options = options;
  }

  get(id) {
    return this.options.app.service('service-b').get(id).then(data => {
      console.log(data);

      return data;
    });
  }
}

class ServiceB {
  get(id) {
    return Promise.resolve({
      id, text: `You have to do ${id}!`
    });
  }
}

const app = feathers()
  .configure(hooks());

app.use('/service-a', new ServiceA({ app }));
app.use('/service-b', new ServiceB());

app.service('service-b').after({
  get(hook) {
    hook.result.hookRan = true;
  }
});

app.service('service-a').get('dishes')
  .then(data => console.log(data));
```

`service-a` is getting the data that ran through the hook.

The problem is most likely not calling the Mongoose model `toObject` before adding fields to the result (Mongoose models do not let you add any additional fields).

**Comment by ryuken** [comment]
Uhm i think the problem is with a mongoose-service.
I don't have to run toObject, because I use the option ```lean : true```
When I use toObject on the hook.result it says it's undefined.
When I do a GET via browser it gives the expected results, but via internal service call it doesn't

**Comment by ryuken** [comment]
I have a strange feeling that the hook is executed in a later stage when the result is already given back. Because in my logs i see the result first and then my console.log("hook ran")

**Comment by daffl** [comment]
It's hard to tell without a way to reproduce. I never encountered this problem using Mongoose.

**Comment by ryuken** [comment]
I'm making a small example project and see if it also happens in there.
I'll post it on github and link it here if I get the same result there

**Comment by vwong** [comment]
@ryuken Some hooks don't execute if there is no `provider` field in the query params.  In your example, try something like:

```
const params = { provider: 'truthyValue' }
gameSessionService.get(id, params).then(g =>  doStuff(g))
````
