### ISSUE TITLE
Using a hook.disable() on a service should remove that from the Allow header for REST services

### ISSUE THREAD

**Issue by sjmcdowall** [feathersjs/feathers-hooks#107]
I disabled a bunch of service calls using hooks.disable() in a before hook call with code like:

```

exports.before = {
    all: [],
    find: [],
    get: [],
    create: [hooks.disable()],
    update: [hooks.disable()],
    patch: [hooks.disable()],
    remove: [hooks.disable()]
};
```

Yet the Allow header still shows all services available:

Allow →GET,POST,PUT,PATCH,DELETE

(From Postman) 

I would think that if we use a stock hook.disable() then the associated Allow header component should be removed as well.

**Comment by daffl** [comment]
Issue moved to [feathersjs/feathers-hooks-common #224](https://github.com/feathersjs/feathers-hooks-common/issues/224) via [**ZenHub**](https://www.zenhub.com/)
