### ISSUE TITLE
Before all and after all hooks

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-hooks#11]
The hooks plugin should provide the ability to also take just a single hook function (instead of an object) which will be applied to all service methods:

```js
app.service('todos').before(function(hook,next) {
  if(!hooks.params.user) {
    return next(new Error('You need to be authenticated'));
  }
  next();
});
```

Additionally it could be very helpful to add general hooks to the application which will be applied to every service (this could be easiliy implemented as a service mixin):

```js
app.before({
  create: function(hook, next) {
    next();
  }
});
```

**Comment by ekryski** [comment]
+1

**Comment by marshallswain** [comment]
I like the array syntax.  For the implementation, it would be nice if `all` would simply add the hooks to each method's queue.  So doing something like this:

```js
myService.before({
	all: [hooks.requireAuth]
});

myService.before({
	create: [hooks.adminOnly]
});

myService.before({
	all: [hooks.removeHelperData]
});
```
would result in `create` having an array of three hooks: [requireAuth, adminOnly, removeHelperData],

while the others would all have only two: [requireAuth, removeHelperData]

**Comment by ekryski** [comment]
@marshallswain: @daffl and I were discussing in the office and thinking that is basically the case. The before `all` hooks would be called *before* the individual service method hooks. The after `all` would fire *after* the individual service method hooks.

Does that make sense? Thoughts?

**Comment by daffl** [comment]
If you define it as an object on your service. What @marshallswain is saying for using `.before` and `.after` in that order will be correct, too though.

**Comment by daffl** [comment]
Although, personally I would prefer this syntax:

```js
myService.before([requireAuth]);

myService.before({
    create: [adminOnly]
});

myService.before([removeHelperData]);
```

But this would make it inconsistent with how it is defined on a service object.

**Comment by marshallswain** [comment]
It sounds like we're all thinking along the same lines.  Consider this syntax:
```js
myService.before({
	all: [requireAuth]
	create: [adminOnly]
});
```

I really like the simplicity of passing the array by itself for all.  Would we also want to support the above and register all first when they come together like this?

**Comment by daffl** [comment]
You're right. Doing that would make it less inconsistent. So here is the API (which shouldn't break the existing):

Array and Object notation. Works for both, when adding a `before` and `after` property to a service object or calling `service.before()` and `service.after()`:

```js
// As an object
var before = {
  all: isAuthenticated, // also as an array [ isAuthenticated ]
  create: [ isAdmin, hashPassword ]
}

// As an array
var before = [ isAuthenticated, isAdmin ]
```

For just calling `service.before()` and `service.after()` additionally also as parameters:

```js
service.before(isAuthenticated, isAdmin)
``

`before.all` will be registered before any other handler *in the current object*. `after.all` will be registered after any other handler *in the current object*. Current object means that something like this:

```js
var myService = {
  find: function(params, callback),
  before: {
    all: isAuthenticated, // also as an array [ isAuthenticated ]
    create: [ isAdmin, hashPassword ]
  }
};

app.use('/myservice', myService);

app.service('myservice').before({
  all: [ foo ],
  create: [ bar ]
});
```

Will register a chain of `[ isAuthenticated, isAdmin, hashPassword, foo, bar ]`.

**Comment by marshallswain** [comment]
That looks good.

**Comment by ekryski** [comment]
:+1: way up!
