### ISSUE TITLE
service.hooks() did not run as expected

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers-hooks#119]
github feathers-hooks master was used

```javascript
const feathers = require('feathers');
const hooks = require('feathers-hooks');
const util = require('util');

const app = feathers()
  .configure(hooks())
  .configure(services);

const log = [];

// a random service is configured

function services () {
  this.use('/messages', {
    before: {
      all: (hook) => { log.push('service.before.all') },
      create: (hook) => { log.push('service.before.create'); }
    },
    after: {
      create: hook => { log.push('service.after.create'); }
    },
    create (data, params) {
      log.push('create method runs');
      return Promise.resolve();
    }
  });
}

// then the stats monitor hooks in

app.service('messages').hooks({
  before: {
    all: (hook) => { log.push('service.hooks.before.all'); }
  },
  after: {
    all: (hook) => { log.push('service.hooks.after.all'); }
  },
  error: {
    all: (hook) => { log.push('service.hooks.error.all'); }
  }
});

// a hook is added dynamically

app.service('messages').after({
  all (hook) { log.push('service.after.all'); }
});

// call a method

const service = app.service('messages');
service.create({ value: 1 }, { query: {} })
  .then(() => console.log(log));
```

gave

```text
[ 'service.before.all',
  'service.before.create',
  'service.hooks.before.all',
  'create method runs',
  'service.after.create',
  'service.hooks.after.all',
  'service.after.all' ]
```

expected was 

```text
[ 'service.hooks.before.all',
  'service.before.all',
  'service.before.create',
  'create method runs',
  'service.after.create',
  'service.after.all',
  'service.hooks.after.all' ]
```

I may be blind again.

**Comment by daffl** [comment]
I'm thinking this is the order it is supposed to. Basically hooks will run in the order they are registered (with `all` hooks that are registered in the same object running before all others) and the `before` and `after` hooks on the service object will register first.

**Comment by marshallswain** [comment]
If that were the case, I would expect the order of the first three to be
```
  'service.before.all',
  'service.hooks.before.all',
  'service.before.create',
```

Before create should not run before all, even if create is registered before all.

**Comment by daffl** [comment]
Only `all` hooks registered _in the same object_ will run before the others in the same object. That's how it has always been. If we change that it would be a breaking change. We can do that for Feathers 3.0.

**Comment by marshallswain** [comment]
oh, I thought *in the same object* was the service object (now that we have been talking about app-level hooks).  So it's actually the same object passed to the hooks function.  I just never noticed it because I always register my hooks in a single object.

**Comment by eddyystop** [comment]
I thought as did @marshallswain. Info, thanks.

From the point of view of the performance monitor/stats, it wants to interate through existing services and add its hooks. Those services will likely have before and after hooks already defined. So for now it can only add its hooks after any existing one.

The problem is the existing before hooks may be doing i/o which the monitor will not be able to time. Likewise in the less likely case after hooks are added dynamically after the monitor hooks in.

I can wait for .first .last to be implemented. Or the monitor can add hooks by inserting to the head of the service's before hook array. The latter case does not cover after hooks added dynamically.
