### ISSUE TITLE
app.hooks() does not pass hook.app

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers-hooks#123]
Add `console.log(Object.keys(hook))` to an `app.hooks()` hook in https://github.com/feathersjs/feathers-hooks/issues/119 . hook.app is not there.

**Comment by daffl** [comment]
I just added tests that make sure that `hook.app` is set in https://github.com/feathersjs/feathers-hooks/commit/298199875fba83b47937047db36e16be452cd232. It looks like it also passed in CI and when I run `Object.keys(hook)`, `'app'` is included.
Maybe you can make sure that `npm ls feathers-commons` gives you a version > `0.7.7` which it should if you run `rm -rf node_modules && npm install`. With older versions it won't set `hook.app`.

**Comment by eddyystop** [comment]
It works. My bad.

I had been transpiling the source from the GitHub branch. I believe I didn't keep the dependencies up to date.
