### ISSUE TITLE
Composing Hooks

### ISSUE THREAD

**Issue by jeffijoe** [feathersjs/feathers-hooks#133]
I suggest adding a compose function to compose multiple hooks together.

Example:

```js
import { composeHooks } from 'feathers-hooks'

export const authenticate = () => composeHooks([
  authentication.hooks.authenticate('jwt'),
  (hook) => {
    hook.params.user_id = hook.params.payload.sub
    return hook
  }
])
```

I've already implemented this.

```js
/**
 * Composes Feathers hooks.
 * @param hooks
 */
export function composeHooks (hooks) {
  return function composed (...args) {
    return hooks.reduce(
      (promise, nextHook) => promise.then(() => Promise.resolve(nextHook.apply(this, args))),
      Promise.resolve()
    )
  }
}
```

Does anyone see anything lacking from this implementation?

**Comment by daffl** [comment]
This is already possible with the `combine` common hook: https://docs.feathersjs.com/v/auk/hooks/common/conditional.html#combine

**Comment by jeffijoe** [comment]
Ah, didn't see that one! I think it would make sense to include that in the feathers-hooks package though

**Comment by daffl** [comment]
The plan is for `feathers-hooks-common` to be the main collection for re-usable hooks (including the ones provided in `feathers-hooks` at the moment) and make the hooks plugin itself part of core (see https://github.com/feathersjs/feathers/issues/408).

**Comment by jeffijoe** [comment]
Cool, thanks!
