### ISSUE TITLE
Calling populate(target, options) is now DEPRECATED

### ISSUE THREAD

**Issue by Kryten0807** [feathersjs/feathers-hooks#141]
I'm seeing a message:

> Calling populate(target, options) is now DEPRECATED and will be removed in the future. Refer to docs.feathersjs.com for more information. (legacyPopulate)

When I follow the [Your First App](https://docs.feathersjs.com/getting-started/readme.html#building-your-first-feathers-app) tutorial and start the app with `npm start`.

Is there any documentation on how to correct this warning?

**Comment by Kryten0807** [comment]
Never mind... apparently I missed it in the documentation. Sorry!

**Comment by CImrie** [comment]
@Kryten0807 Are you able to let me know where you found the solution in the docs? I don't see any replacement for this deprecation, despite it being a very useful feature. Thanks in advance 👍

**Comment by corymsmith** [comment]
@CImrie It's only on the Auk branch of the docs right now: https://docs.feathersjs.com/v/auk/hooks/common/populate.html
