### ISSUE TITLE
how to get service name(path) in hook functions?

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers-hooks#143]
I know in hook functions `this` points to the running service, but I cannot find the service's name/path under `this`?

[EDIT] I'm using feathers-mongoose to create services.

**Comment by beeplin** [comment]
I got it. It's `hook.path` but it is not documented.

**Comment by daffl** [comment]
It is in https://docs.feathersjs.com/v/auk-reorg/api/hooks.html#hook-objects which will be published soon.
