### ISSUE TITLE
Gravatar example doesn't work?!

### ISSUE THREAD

**Issue by PanMan** [feathersjs/feathers-hooks#145]
Hi!
Maybe I'm doing something wrong, but I'm using feathers with feathers-sequalize (latest version from NPM), and when copying the Gravatar example from https://docs.feathersjs.com/getting-started/formatting-and-hooks.html it doesn't work.
I get an error: `info: TypeError: Cannot read property 'email' of undefined`
My model does have an email field, and its properly filled.
I do notice the generated code from `feathers generate hook` is a bit differently structured than the one in the docs.
Generated:
```
module.exports = function(options) {
  options = Object.assign({}, defaults, options);

  return function(hook) {
    hook.gravatar = true;
  };
};
```

Docs:
```
module.exports = function() {
  return function(hook) {
    // Assign the new data with the Gravatar image
    hook.data = Object.assign({}, hook.data, {
      avatar: gravatarImage(hook.data.email)
    });
  };
};
```

However, even the simple generated code fails to add a field to the object.
All I want is to add an URL, based on another field in my object.
Thanks!!

**Comment by daffl** [comment]
Are you sure you added it as a `before` hook to the `create` method (logging `hook.method` should show `create`)?

**Comment by PanMan** [comment]
Oh, sorry, no, that's the only thing I changed, I'm looking for an after hook, not before. Should they be structured differently? I haven't found any example of an after hook that ads a property, even if just a fixed string.

**Comment by daffl** [comment]
In an [after hook](https://docs.feathersjs.com/hooks/usage.html#after-hooks) you can add properties by modifying `hook.result`.

**Comment by marshallswain** [comment]
@PanMan If you want an `after` hook to add a property to the response, simply add it to `hook.result`.  If you want to add it to a db record, you'll have to reference the service that you want to modify by using `app.service('/other/service').patch()` or whatever method you want.

**Comment by daffl** [comment]
You are right, too. I think the Gravatar does make much more sense as an after hook. I will update that in the new guide we are finishing up.

**Comment by PanMan** [comment]
Is there an example anywhere that modifies hook.result? Anything I tried, even just adding a static string, isn't shown eg in the REST api, while I do see the code being called (eg if I log).

**Comment by daffl** [comment]
If you are using Mongoose you need to use `feathers-mongoose` v4.0.0 or later with the default settings (or set `lean: true`). Mongoose models do not allow properties to be added or removed. There are several examples for changing `hook.result` in [the documentation I linked](https://docs.feathersjs.com/hooks/usage.html#as-service-properties).

**Comment by daffl** [comment]
I think we can close this. I kept it open to look into changing the Gravatar to an after hook but I think it can stay the way it already is.

**Comment by PanMan** [comment]
I think as an example it can both be a before or after hook, but I still haven't seen an example with feathers-sequelize that adds a property to the result (eg a gravatar image).

**Comment by marshallswain** [comment]
Try doing 

'''js
hook.result = hook.result.toObject()
hook.result.gravatar = "gravatarURL"
'''

**Comment by PanMan** [comment]
That gives an error:
```
error: Route: / - hook.result.get is not a function
info: TypeError: hook.result.get is not a function
```

**Comment by marshallswain** [comment]
In that case, it should work to just do

```js
hook.result.gravatar = "gravatarURL"
```

The world would face potential collapse if this functionality were broken in Feathers.  😉

**Comment by PanMan** [comment]
Yeah, but it seems most people use feathers with feathers-mongoose, I haven't found any complete and working example for feathers-sequelize for an after hook. Btw, for a find hook, I need to add the field to every item in the result set, right?

**Comment by marshallswain** [comment]
There's only one difference between the databases when it comes to hook functionality: for SQL databases, you have to pre-define your tables.  With MongoDB, there's no concept of a table, which is part of the reason they called it a collection.  I haven't really considered a need for distinguishing between the two, hence no sequelize-specific tutorial.

If you are populating the gravatar to the database (as a before hook), you'll need to add whatever fields in the database.  If you're just adding the result to the response, there's no difference between the two databases, whatsoever.

>  Btw, for a find hook, I need to add the field to every item in the result set, right?
Yes.

**Comment by daffl** [comment]
If you are looking for a complete Sequelize example application, check out https://github.com/BestBuy/api-playground
