### ISSUE TITLE
Test Hooks

### ISSUE THREAD

**Issue by idealley** [feathersjs/feathers-hooks#146]
Is there a way for unit testing hooks?

Pass input data to in and check output, so that we could test our services as well as our custom hooks.

**Comment by daffl** [comment]
Yes. You basically create a mock hook object with the data you need and then make sure that the result is what you'd expect, see

- https://github.com/feathersjs/feathers-chat/blob/master/test/hooks/gravatar.test.js
- https://github.com/feathersjs/feathers-chat/blob/master/test/hooks/process-message.test.js

It is also a good idea to test the hooks integration by making a full service call in a service test (e.g. https://github.com/feathersjs/feathers-chat/blob/master/test/services/messages.test.js) which would look like this:

```js
'use strict';

const assert = require('assert');
const app = require('../../src/app');

describe('\'messages\' service', () => {
  it('registered the service', () => {
    const service = app.service('messages');

    assert.ok(service, 'Registered the service');
  });

  it('creates a message with user id, truncates and adds timestamp', () => {
    return app.service('messages').create({
      text: 'Some <br> text'
    }, {
      user: { _id: 'testId' }
    }).then(message => {
      assert.equal(message.userId, 'testId', 'Set the user id');
      assert.equal(message.text, 'test message &lt;br&gt;');
      assert.ok(message.createdAt, 'Set createdAt property');
    });
  });
});
```

**Comment by idealley** [comment]
Thank you that really helped! Especially the process message test as my hook uses params.

I was already doing test for the hook integration, but wanted to cover the hook itself. 

The documentation explains well how to test services. The generated test are also helpful as a starting point. (although istanbul says that with only the generated test the service is tested 100%)...

**Comment by idealley** [comment]
One question: what is `const { data } = result;` ? I have not seen this before and it returns undefined (I am working on node 6 for compatibility reasons)

Thx

**Comment by daffl** [comment]
It's the ES6 equivalent for `const data = result.data;`. If it is undefined for you you probably do not have pagination enabled.

**Comment by marshallswain** [comment]
The big benefit is that you can do multiple vars really concisely:

```js
const someObject = {
  one: 1, 
  two: 2,
  three: 3
}
const { one, two, three } = someObject
```

**Comment by daffl** [comment]
Also defaults which is awesome:

```js
const someObject = {
  one: 1
}
const { one, two = 3 } = someObject;

one // -> 1
two // -> 3
```

**Comment by idealley** [comment]
That's nice! I will use it right away. 

Yes the undefined was just because I was not returning a Promise. Everything is working now! Thank you for the help.

**Comment by daffl** [comment]
Cool. We'll write this up in a blog post soon, too. @marshallswain already created an issue for this so we'll close this.
