### ISSUE TITLE
[feature request] provide a way to swallow error in error hooks

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers-hooks#151]
Very glad to see the new `error` hook~ It is super useful when handling some 'intentional errors` like key uniqueness checking.

I wonder if it's possible to provide a way to swallow the error (i.e. to cancel the throwing of the error) in the `error` hooks. Maybe just like in `filters`: if an `error` hook returns `false` or resolves with `false` then the error will be swallowed.

This is useful if we already handle the error in the `error` hook and no need to throw it outside.

**Comment by beeplin** [comment]
Or like in `before` hooks: if in `error` hook the `hook.result` is set, then the error is swallowed, and the `hook.result` is returned as if the service method succeeds as normal.

**Comment by daffl** [comment]
One way this is already possible would be to `.catch` the promise and return a normal value instead of throwing another error. So in the hook you could add a `result` property to the `error` object, then check for it in the `catch` and return it like so:

```js
app.service('myservice').create().catch(error => {
  if(error.result) {
    return error.result;
  }

  throw error;
});
```

I think it wouldn't be very hard to add as a feature either. Basically we just have to change https://github.com/feathersjs/feathers-hooks/blob/master/src/hooks.js#L105 to 

```js
.then(hook => {
  if(hook.error) {
    return Promise.reject(hook.error);
  }

  return hook.result;
});
```

**Comment by beeplin** [comment]
@daffl Yes in old days without `error` hooks, I was using `.catch` to do this. However, `.catch` has to be written after the method calling code (as your example shows), and it is way better to hide this kind of logic into `error` hooks so the users of the service just call `app.service('xxx')` and no need to care about the `.catch` thing.

**Comment by daffl** [comment]
This will be available in the next version of Feathers core which will include `feathers-hooks`.

Closed via https://github.com/feathersjs/feathers/pull/621

**Comment by beeplin** [comment]
nice～!
