### ISSUE TITLE
__hooks being overwritten

### ISSUE THREAD

**Issue by Mattchewone** [feathersjs/feathers-hooks#157]
In ref to issue [#154](https://github.com/feathersjs/feathers-hooks/issues/154)

It seems that there is an issue that the test isn't able to test against. 

Comparing the debug output between the main service call and the secondary service.

```
express:router <anonymous>  : /v1/cb001/projects +8ms
feathers-errors NotFound(404): Page not found +1ms
express:router <anonymous>  : /v1/cb001/projects +0ms
finalhandler default 404 +1ms
finalhandler cannot 404 after headers sent +0ms
Error: Can't set headers after they are sent.
  at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
  at ServerResponse.header
....
```

The above is happening after this:
```
{"severity":"INFO","message":"after: projects - Method: find"}
compression no compression: size below threshold +6s
```

It seems as though it is trying to route it again and not finding the route and trying to throw NotFound error but a response has already been set with headers.

**Comment by daffl** [comment]
This is probably not a hooks issue but yeah, I was sure I tested that this is possible but apparently it is not (anymore?) and there are not tests for doing this. We probably want to move this up to https://github.com/feathersjs/feathers

**Comment by Mattchewone** [comment]
@daffl Well the results are returned so the test doesn't fail. The error is only shown in the console, not sure how to test against that? 

Happy to look into it if you could give me some pointers.

**Comment by daffl** [comment]
I'm going to close this to track in the main issue at https://github.com/feathersjs/feathers/issues/566 since the hooks specific issue should be fixed now. I'll have to do a little more digging to give some more useful pointers but we'll definitely get this fixed.
