### ISSUE TITLE
Add hook to the top of others hook

### ISSUE THREAD

**Issue by kozzztya** [feathersjs/feathers-hooks#158]
Is it possible to add a hook to the top of other hooks? Maybe some hack to do this?

**Comment by eddyystop** [comment]
`app.hooks` might perhaps help depending on the details of your use case. You can check hook.path to see which service is being called. https://docs.feathersjs.com/api/hooks.html#application-hooks

Otherwise you'd have to mess with the interal data of the service object which should be avoided.

**Comment by kozzztya** [comment]
Okay, thanks.

**Comment by daffl** [comment]
Also, if you call `app.service('myservice').hooks()` again, those hooks will be added after the existing ones.

**Comment by kozzztya** [comment]
@daffl Yes, but I need to add them before and that's a problem.

**Comment by eddyystop** [comment]
A hook function is a function whose parameter is the `hook` object. Many of the common hooks are as simple as https://github.com/feathersjs/feathers-hooks-common/blob/master/src/services/set-created-at.js

The `combine` hook sequentially calls a set of hook function. So its parameters are functions each of which expects the `hook` object as a parameter. https://docs.feathersjs.com/api/hooks-common.html#combine

You can place a custom hook at the front of the service which mainatins an array of hook functions. You can mutate the array any way you want. Use `combine` after a mutation to form a callable set of hooks functions.

Your custom function, upon being called by a service, just calls the result of that combine.
