### ISSUE TITLE
[discussion] maybe change the name of the context parameter from 'hook' to 'context' or use 'this' in the future?

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers-hooks#159]
Currently the hook function written as `(hook) => {...; return hook; }` is somehow confusing for many new users. The term `hook` has two meanings here: the function itself is called a **hook** or a **hook function**, but the context parameter passed into the hook function is also called `hook`.

In fact the parameter naming is arbitrary, and calling it `hook` is just a convention or a tradition of feathers which is initiated in the official docs. So I propose to (in the future) change the docs and rename it to something more clear, like `context` or so. So people use `context.app`, `context.path` etc. instead of `hook.app`, `hook.path`.

Another possible options is to use `this` instead of a parameter to pass the context object into the hook function. So people just use `this.app` or `this.path` ... I know `this` in hook function used to point to the current service object, so this might have some backward compatibility issues. But on the other hand, today we have the new syntax of arrow functions `=>` which keeps`this` and we don't need to manually bind `this` again and again, which makes the use of `this` in such situation quite concise and elegant and appealing.

**Comment by eddyystop** [comment]
People seem to just not like using `this`. That is the main reason `hook.service` was introduced.

I've also run into (transpiling?) issues passing params with `.call()`. See https://github.com/feathersjs/feathers-hooks-common/issues/140#issuecomment-299227009 and https://github.com/feathersjs/feathers-hooks-common/issues/116 . Thew problem is either me or Babel.

Your comments about 'rationalizing' naming have always been spot on. However it may be wiser to not use `this`.

**Comment by beeplin** [comment]
hmmm, I have never used hooks with babel... I agree `this` might be confusing too and sometimes problematic. How do you think of renaming it to `context`?

**Comment by marshallswain** [comment]
I like the separation of hook = function. Context = hook object

**Comment by eddyystop** [comment]
Context doesn't carry much meaning, so we can do better. Maybe something like `request`, even `package` suggests the thing gets passed along.

**Comment by beeplin** [comment]
I have been considering `request` and `response` before, but I doubt `request` might be too narrow since we also use the term in after hooks and `request.result` doesn't make any sense. If we use `response` in after hooks instead, then `response.data` seems weird too. And they can also be confusing since express/feathers middleware use `request`/`response` for something different, and we often have hooks and middleware in the one project at the same time.

`context` Is the best I can think of so far. Many projects use `context` in similar circumstances such as vue, ajv and etc.

**Comment by daffl** [comment]
I do like `context`. The problem with using `this` is that it already is the service the hook is running on *and* you can't set `this` in ES6 arrow functions (which is one of the reasons we added the `.service` property). I think `request` is too confusing with the HTTP request/response terminology.

**Comment by ekryski** [comment]
FWIW I 100% agree with @daffl's comment. I'd like to see `context`. Also, related https://github.com/feathersjs/feathers/issues/562

**Comment by eddyystop** [comment]
I'm thinking about non-English speakers. Would `state` be easier to
understand?

**Comment by beeplin** [comment]
As a non English speaker I think state might be more ambiguous than context. Context has one and only one specific meaning which is easier to understand.

**Comment by eddyystop** [comment]
The renaming has started with https://github.com/feathersjs/feathers-hooks-common/pull/200 .

An issue has been created for the rest https://github.com/feathersjs/feathers-hooks-common/issues/201 .
