### ISSUE TITLE
Error: 'chck' is not a valid hook method

### ISSUE THREAD

**Issue by geofsb** [feathersjs/feathers-hooks#165]
Can not add hooks on custom service methods other than those specified in ``app.methods`` is this really necessary. I find this limiting.

**Comment by daffl** [comment]
Yes. That is intended because custom service methods are not exposed to the client (see https://docs.feathersjs.com/faq/readme.html#how-do-i-create-custom-methods) and there is no easy way to convert their parameters into a hook object or determine what they return.
