### ISSUE TITLE
Hook typings

### ISSUE THREAD

**Issue by luiza-cicone** [feathersjs/feathers-hooks#166]
I encountered the following problems when typing my hooks:
 - the `id` field is missing form `HookProps`
 - the return types of the hook id `Promise<any> | void` but in the documentation it is specified that a hook object can be returned.

Is there a reason for this? or is it simple typings problem? In which case I would be happy to help.

Thanks!

**Comment by corydeppen** [comment]
According to the [Hook objects doc](https://docs.feathersjs.com/api/hooks.html#hook-objects), there are a few other missing properties, including `service`, `path`, and `error`. These cause an issue when migrating the CLI-generated `logger` hook to TypeScript, as `path` and `error` don't exist on the `HookProps` interface.

/cc @j2L4e

**Comment by j2L4e** [comment]
indeed, I added those to #169

**Comment by daffl** [comment]
Closed via #169
