### ISSUE TITLE
Angular 4 feathers hook build fails - "All declarations of 'Service' must have identical type parameters"

### ISSUE THREAD

**Issue by amalg989** [feathersjs/feathers-hooks#172]
### Expected behavior
Builds angular applciation with feathersjs socket connection to featherjs server without issues.

### Actual behavior
Build failed with a message:

ERROR in [at-loader] ./node_modules/feathers-hooks/index.d.ts:8:13 
    TS2428: All declarations of 'Service' must have identical type parameters.

### System configuration

- Angular 4 (v4.4.4)
- npm 5 (v5.4.2)
- node 8 (v8.6.0)
- webpack (v3.5.5)
- Mac OS Sierra (10.12.6)

Temporary Fix:

remove "extends any" in line 8  found in ./node_modules/feathers-hooks/index.d.ts
> interface Service<T extends any>

**Comment by baljeet** [comment]
Any update on this one? I faced similar issue with feathers and feathers-reactive...

**Comment by baljeet** [comment]
Interestingly enough, the error went away when i updated to version ^2.2.2 for feathers, i checked with the versions on feathers-chat-angular...
See if it works for you as well.

**Comment by daffl** [comment]
This is due to https://github.com/feathersjs/feathers/pull/681 so both modules have to be at the latest version - `feathers-chat-angular` has been updated already via https://github.com/feathersjs/feathers-chat-angular/commit/3dc1339d9d310c9cb4e829c55ae069a040789380
