### ISSUE TITLE
examples not working

### ISSUE THREAD

**Issue by akralj** [feathersjs/feathers-hooks#24]
Hi thanks for feathers, first of all, just discovered it a few days ago. great work.
I'm trying to get hooks working, but no luck for me.
I cloned the rep and tried to run the examples, but i always get:

    var todoService = app.lookup('todos');
    TypeError: undefined is not a function

any idea what could be happening there? I'm on ubuntu 14.04 and node 0.12.7.

**Comment by daffl** [comment]
Thanks for reporting! You are right, the example indeed still ran on Feathers pre 1.0. The correct way to retrieve the service is `app.service('todos')`. I updated both examples in https://github.com/feathersjs/feathers-hooks/commit/6f13d13cfbeb3902ee3f6fbf3c93005433758f3d.

**Comment by akralj** [comment]
@daffl your right, it' s changed.  i must have look at a cached page. all good :)
