### ISSUE TITLE
Defining a service hook without an app/before app initialization?

### ISSUE THREAD

**Issue by dbkaplun** [feathersjs/feathers-hooks#25]
I'd like to define a hook without calling `app.service('name')`, directly on the service. Something like this:
```js
var User = knex('user', config.feathersKnex).extend({
  before: {
    create: [authHooks.hashPassword('password')]
  }
});
```

Is this possible? It seems like if I run that code, the hook is simply ignored.

**Comment by daffl** [comment]
Not at the moment. The hook and event magic happens when registering the service with the Feathers app and is only available on the wrapped service object (which you get via `app.service('name')`).
Is the problem that you don't want to expose the service publicly?

**Comment by dbkaplun** [comment]
It's no problem I suppose. I was hoping to be able to treat the resultant object from the `knex()` call as a Model in its own right but I suppose I can work with the service object that presumably goes through an HTTP-like middle layer. My original design involved creating a `models/` directory with one model per file, that I could simply work with directly without needing access to the HTTP server. I suppose I could instead make a `services/` directory whose files export something like:
```js
var service;
module.exports = function getUserService (app) {
  if (service) return service;
  // if the service was already configured, return it, otherwise create it
  app.use('/api/users', knex('user', config));
  service = app.service('/api/users');
  service.before({create: [authHooks.hashPassword('password')]});
  return service;
};
```

Is that more along the lines of how a feathers model should be implemented?

**Comment by daffl** [comment]
You can still do something like this in `sevices/user.js`:

```js
module.exports = knex('user', config.feathersKnex).extend({
  before: {
    create: [authHooks.hashPassword('password')]
  }
});
```

This will use the hooks defined there when registering the service. And then in `services/index.js`:

```js
var userService = require('./users');

module.exports = function() {
  var app = this;
  app.use('/users', userService);
}
```

In `app.js`:

```js
var services = require('./services');
app.configure(services);
```

We're working on an application generator with a recommended setup at https://github.com/feathersjs/generator-feathers/tree/app-architecture/app/templates/static/src which should hopefully be available soon.

**Comment by ekryski** [comment]
Closing as this is now possible. You can define your hook whenever and then just register it when you need it.

```
var myHook = require('my-hook');
app.service('users').before({create: myHook});
```

**Comment by thomas-p-wilson** [comment]
I know I'm raising the dead here, but this is definitely the most relevant ticket for the issue that I'm facing, and to me it makes sense to keep it here.

I've been working on implementing GraphQL in my application, and I want to use my feathers services, and the functionality contained in their hooks, as the GraphQL resolvers. Now, when the full application is running, this is no problem. The models, their services, and the hooks are all defined before the GraphQL stuff is initialized, but I was hoping that there might be some way during testing to create _just_ the services+hooks without having to configure my application. Any thoughts on the matter?

**Comment by daffl** [comment]
The way to do it is to create the app you need with the services you want during initialization of the test. This is done in most Feathers test (e.g. [this one](https://github.com/feathersjs/feathers-rest/blob/master/test/index.test.js)).

**Comment by eddyystop** [comment]
The Basics guide was updated a while ago to recommend the same thing. https://docs.feathersjs.com/guides/step-by-step/basic-feathers/testing-hooks.html

**Comment by thomas-p-wilson** [comment]
Gotcha. It's what I've been doing. Was just hoping there was another,
simpler, leaner way. But all good. Thanks folks!
