### ISSUE TITLE
Should support promises returned from service methods

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-hooks#28]
Fairly important for Feathers 2. The way Hooks currently work and due to the async processing in the overwritten methods, Promises originally returned from a service will be swallowed by a before and after hook and the callback will be used instead (this will al ways work because of Feathers promise normalization). We should instead migrate Hooks to be completely promise compatible which will also make for nicer synchronous APIs without needing `next` like:

```
app.service('todos').before({
  create(hook) {
    if(!hook.data.text) {
      throw new Error('Text has to be provided');
    }

    hook.data.text = data.text.substring(0, 255);
  }
});
```

**Comment by ekryski** [comment]
Ya totally. I had actually thought about this when I was migrating the db adapters.

**Comment by daffl** [comment]
I have a branch that does allthethings at least for `.before` hooks at https://github.com/feathersjs/feathers-hooks/tree/promises-28.
