### ISSUE TITLE
Make sure hook promises propagate their errors

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-hooks#30]
@aroc pointed out that promises with a final `.catch` can swallow their errors which means that hooks chained like

```
app.service('todos').before({
   create(hook) {
      throw new Error('Some error');
   }
});

app.service('todos').before({
   create(hook) {
      hook.shouldRun = false;
   }
});
```

May not work as expected.

**Comment by ekryski** [comment]
Maybe we can also verify that they go through sockets as expected at the same time?

https://github.com/feathersjs/feathers-errors/issues/1

**Comment by ekryski** [comment]
I'm pretty sure they are working ok. At least in every case I'e had so far the error propagate through the hook chain. @daffl can we close this?

**Comment by daffl** [comment]
Yep. I didn't run into any issues yet either. Closing this one.
