### ISSUE TITLE
Provide a collection of common hooks

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-hooks#31]
Already suggested by @marshallswain in https://github.com/feathersjs/feathers-commons/issues/13 `feathers-hooks` should provide a small collection of common hooks. I am currently thinking of:

- Remove field
- Timestamp (`updatedAt`, `createdAt` etc.)
- Disabling methods (which should take care of https://github.com/feathersjs/feathers/issues/106)

Any others?

**Comment by ekryski** [comment]
:+1: Keep in mind that some of the db adapters already support updatedAt, createdAt at the model level. Namely, feathers-mongoose and feathers-sequelize

**Comment by daffl** [comment]
Is that optional or do they always add those fields? I'm not sure what other hooks we may need. Maybe something that calls a `toJSON` or `serialize` method? @marshallswain any other ideas?

**Comment by marshallswain** [comment]
I already added a toJSON hook to feathers-mongoose.  It would probably be useful to go over the auth hooks that are in feathers-authentication.  We could also create a send email hook for mandrill or an SMS hook for Twilio.

**Comment by marshallswain** [comment]
The SMS hook would be good for a two-factor auth scenario.

**Comment by daffl** [comment]
I meant more basic hooks that don't require another dependency and can go into this repository.

**Comment by marshallswain** [comment]
Oh right.  Getting carried away.  We could do a `setField('fieldName', value')` hook.

**Comment by marshallswain** [comment]
I can't think of anything else right now.  We can always add more as we discover them.

**Comment by ekryski** [comment]
@daffl sequelize automatically adds those attributes. With mongoose if put them in your schema and set `defalt: Date.now` you'll get them populated on first save. You can then either use a feathers hook or mongoose "pre save" middleware to update the `updatedAt` attribute.

Ya, @marshallswain I think all those ideas are totally valid but they probably don't belong in this repo. I'm actually thinking that the list of "common" hooks is pretty short. Really the hooks should probably be packaged with the related service. For example, Twilio hooks, Stripe hooks, Auth hooks, Mailer hooks, etc.

**Comment by marshallswain** [comment]
Yep.  That makes sense.  I just get a little overexcited about this stuff (like that's even possible :)

**Comment by marshallswain** [comment]
I've started this here: https://github.com/feathersjs/feathers-hooks/pull/33

**Comment by marshallswain** [comment]
Maybe id mapping is another one: https://github.com/feathersjs/feathers-nedb/issues/11

**Comment by daffl** [comment]
That could maybe just be done with an `addProperty` hook:

```js
app.service('todos').after({
  find: hooks.addProperty('id', data => data.id)
});
```

**Comment by marshallswain** [comment]
Yeah.  We would need one for params going in and one for data coming out.

**Comment by marshallswain** [comment]
Or wait. Do all of the adapters let you define an id property?

**Comment by daffl** [comment]
I would just make it depend on the `hook.type` if it's `before` modify `hook.data` if it's `after` modify `hook.result`. Also, if it's a `find` method iterate over every item.
