### ISSUE TITLE
The idea for a new hook

### ISSUE THREAD

**Issue by kulakowka** [feathersjs/feathers-hooks#42]
I have an idea for a new hook. Quite often it is necessary to validate of modify fields from `request.body`.

We can use [string](https://www.npmjs.com/package/string) package for string validation and transformation . 

It provides such methods as: 
- camelize()
```javascript
S('data_rate').camelize().s; //'dataRate' 
S('background-color').camelize().s; //'backgroundColor' 
S('-moz-something').camelize().s; //'MozSomething' 
S('_car_speed_').camelize().s; //'CarSpeed' 
S('yes_we_can').camelize().s; //'yesWeCan' 
```
- capitalize()
```javascript
S('jon').capitalize().s; //'Jon' 
S('JP').capitalize().s; //'Jp' 
```
- escapeHTML() 
```javascript
S('<div>hi</div>').escapeHTML().s; //&lt;div&gt;hi&lt;/div&gt; 
```
- slugify()
```javascript
S('Global Thermonuclear Warfare').slugify().s // 'global-thermonuclear-warfare' 
S('Crème brûlée').slugify().s // 'creme-brulee' 
```
- and many other...

As a bonus - we have the methods for validation of the box.
- isAlpha()
```javascript
S("afaf").isAlpha(); //true 
S('fdafaf3').isAlpha(); //false 
S('dfdf--dfd').isAlpha(); //false 
```
- isAlphaNumeric()
```javascript
S("afaf35353afaf").isAlphaNumeric(); //true 
S("FFFF99fff").isAlphaNumeric(); //true 
S("99").isAlphaNumeric(); //true 
S("afff").isAlphaNumeric(); //true 
S("Infinity").isAlphaNumeric(); //true 
S("-Infinity").isAlphaNumeric(); //false 
S("-33").isAlphaNumeric(); //false 
S("aaff..").isAlphaNumeric(); //false 
```
- isEmpty()
```javascript
S(' ').isEmpty(); //true 
S('\t\t\t    ').isEmpty(); //true 
S('\n\n ').isEmpty(); //true 
S('helo').isEmpty(); //false 
S(null).isEmpty(); //true 
S(undefined).isEmpty(); //true 
```

It can looks like:
```javascript
app.service('users').before({
  create: [
    hooks.transform({
      // The most frequently used transformations can provide of the box.
      email: {
        trim: true,
        lowerCase: true,
        // validations too
        isAlphaNumeric: true,
        isEmpty: false        
      },
      // Custom transformation can be implemented using the function
      username: (v) => v.toLowerCase(),      // sync transformation
      password: (v) => Promise.resolve(v)    // async transformation
    })
  ]
})
```

I think I can try to implement this functionality. This will solve the problem of validation and transformation of data once and for all :)

**Comment by kulakowka** [comment]
<img width="996" alt="2016-02-20 19 12 32" src="https://cloud.githubusercontent.com/assets/557190/13197678/eb61f9bc-d805-11e5-9a05-6bd9833a0ccf.png">

Work started. Once I completed yet to show you a working version.

**Comment by marshallswain** [comment]
👍

**Comment by kulakowka** [comment]
You can follow the progress here: [kulakowka/feathers-validate-hook](https://github.com/kulakowka/feathers-validate-hook)

I am now actively working on it. And it seems to be cool!

**Comment by kulakowka** [comment]
I want to create first version with [string](https://www.npmjs.com/package/string) package. Validations for date, integer, etc.. will be implemented too.

**Comment by kulakowka** [comment]
After I do the first version, I think about in order to use different versions of the validators. However, my main goal is to make a complex solution for validation and data transformation. If it will do other libraries for validation may not be necessary.

**Comment by enten** [comment]
:+1:  great idea

**Comment by kulakowka** [comment]
I have created some packages:
https://github.com/kulakowka/feathers-transform-hook
https://github.com/kulakowka/feathers-validate-hook

**Comment by ekryski** [comment]
:+1: awesome. Looking forward to trying them out!
