### ISSUE TITLE
Create a `populate` hook

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-hooks#56]
It's really common to populate related entities. This hook would probably take a service `name` and an `id` and then automatically populate a value.

For example:

```js
const defaults = {};

module.exports = function(options) {
  options = Object.assign({}, defaults, options);

  return function(hook) {
    if (hook.type === 'after') {
      return new Promise((resolve, reject) => {

        function populateSender(message) {
          return hook.app.service('users').get(message.sentBy, hook.params).then(user => {
            message.sentBy = user;
            return message;
          }).catch(reject);
        }

        if (Array.isArray(hook.result.data)) {
          return Promise.all(hook.result.data.map(populateSender))
            .then(data => {
              hook.result.data = data;
              resolve(hook);
            }).catch(reject);
        }
        // Handle single objects.
        else {
          populateSender(hook.result).then(message => {
            hook.result.data = message;
            resolve(hook);
          }).catch(reject);
        }
      });
    }
  };
};
```

**Comment by kulakowka** [comment]
Thank you @ekryski . this is what I need now!

**Comment by naptiv** [comment]
@ekryski sender is not populated at creation 
@https://github.com/feathersjs/feathers-react-native-chat/blob/master/Application.js

**Comment by naptiv** [comment]
@ekryski 
Run into a weird issue at https://github.com/feathersjs/feathers-react-native-chat/issues/6 with this hook / socket events

**Comment by arao456** [comment]
@ekryski I think I'm still running into the issue above. I've been pulling out my hair trying to get this fixed but I don't know what I'm missing.

```
//package.json
    ...
    "feathers-hooks": "^1.4.0",
```

I modified `populateSender` to just return the user information, and the relevant code is
```
// Handle single objects.
        else {
          populateSender(hook.result).then(user => {
            hook.result.user = user;
            console.log(hook.result, hook.result.user);
            resolve(hook);
          }).catch(reject);
        }
```
Logging `hook.result` returns the result without the user info, but logging `hook.result.user` returns the correct user object. I'm at a loss as to what is going on here.

**Comment by ekryski** [comment]
@arao456 you probably need to call `toJSON` if you are using sequelize or `toObject` if you are using mongoose. Those two ORMs return models and so you can't modify the model. So that's my hunch. I'm not doing that in the example because I pulled that from a codebase that is using the `lean: true` option which always returns regular objects.

Let me know if that works. We do have [a mention in the docs](http://docs.feathersjs.com/databases/mongoose.html#modifying-results-with-the-toobject-hook) but I think we'll need to find a way to make it more clear.

I'll try and actually get this hook out in the next day or so and in it, it should probably just call either `toObject` or `toJSON` for you if you haven't already.

**Comment by daffl** [comment]
This has been closed for now via https://github.com/feathersjs/feathers-hooks/pull/60. Will need to iterate and refine a little with some follow-up issues.
