### ISSUE TITLE
Header or request information in hooks

### ISSUE THREAD

**Issue by RickEyre** [feathersjs/feathers-hooks#61]
Is there a way to access this in a hook? If not, would this be possible?

**Comment by ekryski** [comment]
@RickEyre Yes these are accessible.

On the client they are just under `hook.params.headers`, they will get passed appropriately to your REST client transport (ie. superagent, request, etc.)

On the server see: http://docs.feathersjs.com/middleware/express.html#setting-service-parameters

**Comment by ekryski** [comment]
I'm going to assume you are good based on my last comment. We can re-open if necessary.

**Comment by RickEyre** [comment]
Yes, forgot to respond back, sorry. Thanks for the answer :)

**Comment by parnurzeal** [comment]
I can't seem to find hook.params.headers.
When I printed out, it is `undefined`.

Maybe something got changed?

**Comment by ekryski** [comment]
@parnurzeal on the client or on the server. On the server they will not exist unless you use an Express middleware like this:

```js
function(req, res, next) {
  req.feathers.headers = req.headers;
  next();
}
```

**Comment by brianyang** [comment]
@ekryski - i'm on the server, and hooks.params is always empty. i'm coming from the graphql endpoint and using the hooks in the services, but params is always empty. 

trying to figure out exactly where to put that middleware function. could you give me a better idea? 

thanks for your help

**Comment by brianyang** [comment]
to anybody coming to this thread, i got this to work by defining a function and using that as middleware. 

```js
app.use('/graphql', middleware, graphqlExpress((req) => {})

function middleware(req, res, next) {
  req.feathers.headers = req.headers;
  next();
}
```

**Comment by TylerYang** [comment]
same here, after adding `req.feathers.headers = req.headers` in my middleware, all I got in `hook.headers` is an `undefined` object. am I missing anything? @ekryski 

by the way, I am using `2.1.1` featherjs and `1.8.1` for feather-hook

**Comment by daffl** [comment]
The data you are looking for will be in `hook.params.headers` (not `hook.headers`).

**Comment by elixiao** [comment]
why can't get headers when the path is specified:

`
app.use('/path',function(req, res, next) {
  req.feathers.headers = req.headers;
  next();
})
`

while the following code still works:

`
.use(function(req, res, next) {
	req.feathers.headers= req.headers;
	next();
})
`

@ekryski @daffl

**Comment by marshallswain** [comment]
That should work as long as you're declaring that before any other use of `/path`.

**Comment by elixiao** [comment]
```
.use(function (req,res,next) {
	req.feathers.a = 'a';
	next()
})
.use('/path',function (req, res, next) {
	req.feathers.b = 'b' ;
	next();
})
.use('/path',function(req, res, next) {
	req.feathers.c = 'c';
	app.handle(req, res);
})
```

I found only a is in params, b and c are lost. @marshallswain

**Comment by daffl** [comment]
You can if you register it at the same time as the service:

```js
app.use('/path', function(req, res, next) { req.feathers.headers = req.headers; next(); }, service)
```

Ideally as also [pointed out in this FAQ](https://docs.feathersjs.com/faq/readme.html#how-do-i-access-the-request-object-in-hooks-or-services) the service method calls should stay as transport independent as possible however.

**Comment by kfern** [comment]
Same here. I have 
```
  app.use(function(req, res, next) { 
    req.feathers.fromMiddleware = 'Hello world';
    req.feathers.headers = req.headers; 
    next(); 
  })
```
before app.use(notFound()); in src/middleware/index.js

In service hook, console.log(hook.params) show:
```
{ query: {}, provider: 'socketio' }
```
What am I doing wrong? 

Thanks in advance

**Comment by daffl** [comment]
You have to register that middleware _before_ any service.

**Comment by kfern** [comment]
@daffl. Thanks for for your help but I can't get it to work.

middleware.js is registered after the services in app.js. I've tried it in app.js before app.configure (services); but does not change the result. Where should it be put?
```
app.use(function(req, res, next) { 
  req.feathers.fromMiddleware = 'Hello world';
  req.feathers.headers = req.headers; 
   next(); 
});//Same result
// Set up our services (see `services/index.js`)
app.configure(services);
// Configure middleware (see `middleware/index.js`) - always has to be last
app.configure(middleware);
app.hooks(appHooks);
```

**Comment by marshallswain** [comment]
What other plugins are you registering before this?

**Comment by kfern** [comment]
None. It is a new generated app

**Comment by marshallswain** [comment]
I think you'll need at least this much before that for this to work:

```js
import feathers from 'feathers';
import bodyParser from 'body-parser';
import rest from 'feathers-rest';
 
const app = feathers()
  .configure(rest())
  .use(bodyParser.json())
  .use(bodyParser.urlencoded({ extended: true }))
  .use(function(req, res, next) {
    req.feathers.data = 'Hello world';
    next();
  });
```

**Comment by daffl** [comment]
What @marshallswain posted should work. It is definitely being tested in https://github.com/feathersjs/feathers-rest/blob/master/test/index.test.js#L399

**Comment by kfern** [comment]
Hi :-)

The "feathers generate app" command creates a different source code. 

app.configure(rest()) is after .use(bodyParser.urlencoded({ extended: true })), so test fails: https://travis-ci.org/kfern/test-feathers-hooks-issues-61/builds/242706813

**Comment by daffl** [comment]
Interesting, we'll have to look into it. Can you create an issue in https://github.com/feathersjs/generator-feathers/ so this doesn't get lost?

**Comment by kfern** [comment]
Done :-)

**Comment by kfern** [comment]
Here again @daffl
 
Adding in src/middleware/index.js  
```
  app.use(function(req, res, next) {
    req.feathers.data = 'Hello world';
    next();
  });
```
req.feathers is undefined in middleware/index.js, so test fails. with 500 error: https://travis-ci.org/kfern/test-feathers-hooks-issues-61/jobs/245581258

Test repo: https://github.com/kfern/test-feathers-hooks-issues-61/blob/master/src/middleware/index.js#L7

**Comment by daffl** [comment]
Will be fixed via https://github.com/feathersjs/generator-feathers/pull/232. Just move your `app.configure(middleware);` *after* `app.configure(rest());`

**Comment by kfern** [comment]
Ok. Now the tests do not fail, but the data is not available. In a before all hook, console.log(hook); return {}

https://github.com/kfern/test-feathers-hooks-issues-61/blob/master/src/middleware/index.js#L8
https://github.com/kfern/test-feathers-hooks-issues-61/blob/master/src/app.hooks.js#L8
https://github.com/kfern/test-feathers-hooks-issues-61/blob/master/src/hooks/test-61.js

**Comment by daffl** [comment]
I just created a new app with `feathers-cli@2.2.1`, then a middleware like:

```js
module.exports = function (options = {}) {
  return function test(req, res, next) {
    req.feathers.message = 'Hello world';
    next();
  };
};
```

And a `before` all hook like

```js
module.exports = function (options = {}) { // eslint-disable-line no-unused-vars
  return function (hook) {
    console.log(hook.params);
    // Hooks can either return nothing or a promise
    // that resolves with the `hook` object for asynchronous operations
    return Promise.resolve(hook);
  };
};
```

And it shows `message: 'Hello world'` when going to the service endpoint.

**Comment by kfern** [comment]
Hi @daffl 

It's working for me now! Thanks for the nice and direct feedback :-)

I followed these steps:

$ feathers -V
2.2.1

feathers generate app
feathers generate middleware (middleware-test-61)
feathers generate service (service-test-61)
feathers generate hook (hook-test-61, before all service-test-61)
https://github.com/kfern/test-feathers-hooks-issues-61/commit/5b22ba6043854971504c8d95af73a26683511d5f

Added req.feathers.message = 'Hello world'; in src/middleware/middleware-test-61.js
Added console.log(hook.params); in src/hooks/hook-test-61.js
https://github.com/kfern/test-feathers-hooks-issues-61/commit/f6a68909ba98c3f3b1d34d6975d10e225740d374

Test's output:

ok 1 Feathers application tests starts and shows the index page
middleware-test-61 middleware is running
ok 2 Feathers application tests 404 shows a 404 HTML page
middleware-test-61 middleware is running
ok 3 Feathers application tests 404 shows a 404 JSON error without stack trace
**undefined**
ok 4 'hook-test-61' hook runs the hook
ok 5 'service-test-61' service registered the service
https://travis-ci.org/kfern/test-feathers-hooks-issues-61/jobs/245929395

Request http://localhost:3030/service-test-61 with Postman:

info: Feathers application started on localhost:3030
middleware-test-61 middleware is running
**{ query: {}, provider: 'rest', message: 'Hello world' }**
info: after: service-test-61 - Method: find

**Comment by kfern** [comment]
Using feathers-client and socket.io-client, console.log(hook.params) output is
```
{ query: {}, provider: 'socketio' }
info: after: service-test-61 - Method: find
```
Is the expected behavior?

feathers-client and socket.io-client versions are:
```
<script src="//npmcdn.com/feathers-client@^2.0.0-pre.1/dist/feathers.js"></script>
<script src="//unpkg.com/socket.io-client@1.7.3/dist/socket.io.js"></script>
```

**Comment by daffl** [comment]
Glad it worked and yes, that is expected. Socket middleware has to be [registered with their own provider](https://docs.feathersjs.com/api/socketio.html#middleware-and-service-parameters).

**Comment by kfern** [comment]
Ok. Thanks again
