### ISSUE TITLE
Bundled hooks should support a scope

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-hooks#63]
If you manipulated your `result` object so that the property you want to remove is not at the root level or inside `result.data` as an array then it won't be removed. This is the case with auth. We set the response to be:

``` js
{
  token: 'token',
  data: {
    email: 'admin@feathersjs.com',
    password: 'password'
  }
}
```

The password won't be removed when using the current `remove` hook. Ideally, the response from auth should be:

``` js
{
  token: 'token',
  user: {
    email: 'admin@feathersjs.com',
    password: 'password'
  }
}
```

but because we cannot scope the fields to be removed they still won't be using the remove hook. The same goes for the other hooks that manipulate data.

**Comment by ekryski** [comment]
oops. Accidentally closed.

**Comment by daffl** [comment]
[feathers-hooks-common](https://github.com/feathersjs/feathers-hooks-common) no support this (and v1.6.0 of feathers-hooks which uses hooks-common as its bundled hooks).
