### ISSUE TITLE
How to mix hooks together (pluck + populate)

### ISSUE THREAD

**Issue by quick691fr** [feathersjs/feathers-hooks#68]
Imagine you have user objects and company objects. Company contains a reference to a user.

What's the better way to achieve mixing hooks like calling the "pluck" hook inside a "populate" hook to make the populate of company's get method sending a result containing only few properties of user instead the full user object ?

I can't use user after hook because my user get method called out the company context should return all the user fields.

I achieved that with a new service based on the same model as user and implementing only the get method with a "pluck" after hook. The problem is that it leads on multiple services used only to filter data which is messy.

**Comment by ekryski** [comment]
@quick691fr being totally honest, I'm not sure. Those built in hooks are a bit newer so I haven't run into that situation yet. Usually I just get the objects back (in your case the user objects populated on the company) and rip through them in side a custom hook to serialize the way that I want.

I'm pretty positive you can just call a hook directly from inside another hook or at least dynamically add one before the service call and then dynamically remove it afterwards. I just haven't had time to try it.

The second option is basically [what we are doing here](https://github.com/feathersjs/feathers-hooks/blob/master/test/bundled.test.js#L45). It feels hacky but it might be what you are looking for in the short term.

**Comment by eddyystop** [comment]
`feathers-hooks-common` has introduced a new hook `combine` which should handle this issue.

```javascript
/**
 * Hook to execute multiple hooks
 *
 * @param {Array.function} rest - Hook functions to execute.
 * @returns {Object} resulting hook
 *
 * Example 1
 * service.before({
 *   create: hooks.combine(hook1, hook2, ...) // same as [hook1, hook2, ...]
 * });
 *
 * Example 2 - called within a custom hook function
 * function (hook) {
 *   ...
 *   return hooks.combine(hook1, hook2, ...).call(this, currentHook)
 *     .then(hook => { ... });
 * }
 */
```
