### ISSUE TITLE
Be able to access deeply nested attributes in bundled hooks

### ISSUE THREAD

**Issue by mcchrish** [feathersjs/feathers-hooks#79]
Is it possible for remove hook to delete inner objects like:

```
{
  product: {
    prodInfo: 'info'
  }
}
```

`hooks.remove('product.prodinfo')`

**Comment by ekryski** [comment]
Not yet but this is something that we want to add to all of the hooks. That you can reference nested attributes.

In the interim you need to write your own custom hook or make a PR?? 😁

**Comment by mcchrish** [comment]
Thanks for the advise.
For now, I'll try writing my own simple hook first. I'll see if putting up a PR is in my range 👍

**Comment by halfjust** [comment]
Testing with the version 1.5.6, it works only after I added 'dataValues' before the property, this behavior is correct?

**example what went wrong:**
`hooks.remove('id')` 
**error message:** Cannot read property 'id' of undefined


**example that worked:**
`hooks.remove('dataValues.id')`

**used object:**
```
[
  {
    "id": 1
    "name": "Name 1"
  },
  {
    "id": 2
    "name": "Name 2",
  }
]
```

**Comment by eddyystop** [comment]
The bundled hooked will be deprecated soon in favor of `feathers-hooks-common`. The hooks in the latter support dot notation for reaching into objects.

**Comment by ekryski** [comment]
@eddyystop once your docs get merged feel free to close this issue.

**Comment by eddyystop** [comment]
GitBook is live again ... sorta.
