### ISSUE TITLE
Throw or log an error for catch block in populate method.

### ISSUE THREAD

**Issue by jondcoleman** [feathersjs/feathers-hooks#80]
In this bit of code (bundled.js) :

```js
// If the relationship is an array of ids, fetch and resolve an object for each, otherwise just fetch the object.
var promise = Array.isArray(id) ? Promise.all(id.map(function (objectID) {
  return hook.app.service(options.service).get(objectID, hook.params);
})) : hook.app.service(options.service).get(id, hook.params);
return promise.then(function (relatedItem) {
  if (relatedItem) {
    item[target] = relatedItem;
  }
  return item;
}).catch(function () {
  return item;
});
```

the catch function doesn't give any indication that something went wrong.  I spent several hours debugging this to finally figure out that it was my `auth.restrictToOwner({ ownerField: '_id' })` hook which was causing the `populate` method not to work (since the promise was rejected).  It just kept returning the original result and I couldn't figure out why it wasn't working.

Would it be possible to log or throw an error in the catch here?  Or is there another way I should have known what was happening?

Thanks!

**Comment by daffl** [comment]
I have no idea why I put that in there at all. I'm pretty sure that catch can be completely removed. Would you mind submitting a pull request? If the tests are passing we'll make a patch release right away.

**Comment by jondcoleman** [comment]
@daffl Looks like a fix was included in https://github.com/feathersjs/feathers-hooks/pull/81

Thanks!

**Comment by daffl** [comment]
Yep. Closed via https://github.com/feathersjs/feathers-hooks/pull/81. Thanks @t2t2!

**Comment by jondcoleman** [comment]
Yep, thanks!
