### ISSUE TITLE
Remove ref doc will broke the parent router

### ISSUE THREAD

**Issue by crapthings** [feathersjs/feathers-hooks#82]
let's have service A and service B
when A has many B

   A: { childrenIds: [1, 2, 3] }

then you use populate hook on A like

```
const findPatents = hooks.populate('children', {
  service: 'B',
  field: 'childrenIds'
})
```

you remove any B will cause A router "404 not found"

is this consider a bug ?

**Comment by daffl** [comment]
I'm not sure what else it should do? It could probably throw a more specific error like `Error populating 'children': <error message here>`.

**Comment by daffl** [comment]
This should no be handled in the new populate hook in [feathers-hooks-common](https://github.com/feathersjs/feathers-hooks-common).
