### ISSUE TITLE
Hooks cannot remove inherited properties

### ISSUE THREAD

**Issue by supasate** [feathersjs/feathers-hooks#89]
I use `feathers-mongoose` and try to remove `password` field with `after hook` but it doesn't work. 

I found that it's caused by [containsField() and removeField() method](https://github.com/feathersjs/feathers-hooks/blob/db68ef7f877ed92008f678e97f8ef58f573737ec/src/bundled.js#L102-L119) that use `hasOwnProperty()` to check for property existence. However, properties in an object from `feathers-mongoose` are inherited properties which `hasOwnProperty()` will return `false`. 

I will make an PR to solve this issue by searching through the prototype chain to remove inherited properties.

**Comment by daffl** [comment]
The PR looks like a good change (I just had one comment on how I think it could be made much shorter 😉 ).

However, using Mongoose I also recommend converting the result to an object first using the `toObject` hook or `lean` option before using it with other hooks.

**Comment by supasate** [comment]
Oh, right. The mongoose service provides `toObject` hook. I forgot that it's already noted in the doc. Thank you for your advice ^^.

So, then, my PR will be for general case of inherited properties. I commented the code back.
