### ISSUE TITLE
Be able to apply hooks to custom service methods

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-hooks#9]
I'd like to be able to have a service like so:

```js
var myCustomHook = function(hook, next){
  // do something custom
  next();
};

var CustomService = Service.extend({
    before: {
      customMethod: [myCustomHook]
    },

    customMethod: function(params, cb){
      // Do some custom stuff
      cb();
    }
});
```

Currently hooks only fire on our default service methods.

**Comment by daffl** [comment]
Closing this one as we discussed in #10 that it doesn't make too much sense (at least currently).

**Comment by kbrandwijk** [comment]
I'm sorry to revive this old issue, but has anything changed with regards to this? It still feels useful to be able to attach hooks to any method a service has. Also, ES6 might have offered a few ways by now (like the spread operator) to not needing to know the exact signature of the custom service method?
