### ISSUE TITLE
Customize existing hook - 'this' undefined - TypeError

### ISSUE THREAD

**Issue by jorgelopezs** [feathersjs/feathers-hooks#94]
I'm trying to add features to an existing hook. I'm following the last example from [HERE](http://docs.feathersjs.com/hooks/usage.html). I get a 'TypeError can't call a method of undefined'.

I have debugged and managed to find that **'this'** is undefined inside auth.restrictToOwner(). **'this'** is defined in my hookWrapper scope. What is the cause of this?

#### My code is below

```javascript

const auth = require('feathers-authentication').hooks;

exports.hookWrapper = function(options){
    // 'this' is populated
    return function(hook){
    // 'this' is populated
    
        return new Promise(function(resolve, reject){
            //call restrictToOwner()
            auth.restrictToOwner(options)(hook).then(function(hook){
                resolve(hook);
            }).catch(function(error){
                // I get error here 
                // TypeError can't call method 'get' of undefined
                
                reject(error);
            });
        
        });
    };
};


//In my service I call it like this
const globalHooks = require('../../../hooks');

exports.before = {
    get : [
        globalHooks.hookWrapper()
    ]
};


```

**Comment by marshallswain** [comment]
Which db adapter?

**Comment by jorgelopezs** [comment]
feathers mongoose

**Comment by corymsmith** [comment]
@jorgelopezs Are you sure its that line thats failing? And not https://github.com/feathersjs/feathers-authentication/blob/master/src/hooks/restrict-to-owner.js#L30

Not sure why either would be happening but just trying to track down where its happening.

**Comment by jorgelopezs** [comment]
This is the exact error I get on the `catch`.
```
[TypeError: Cannot read property 'get' of undefined]
```

**Comment by jorgelopezs** [comment]
I'm running node v5.5.0

**Comment by jorgelopezs** [comment]
This is the value of options at L30 in restrict-to-owner.

```
{ idField: '_id',
  ownerField: 'userId',
  shouldSetupSuccessRoute: true,
  shouldSetupFailureRoute: true,
  successRedirect: '/auth/success',
  failureRedirect: '/auth/failure',
  tokenEndpoint: '/auth/token',
  localEndpoint: '/auth/local',
  userEndpoint: '/users',
  header: 'authorization',
  cookie: { name: 'feathers-jwt', httpOnly: false, secure: false },
  token: { secret: 'zN59fyL5SLYdyxfFVDLKVtlayZ5g+ngOjlhEibKA7hD+MnnDJVBw3oh3NfjJPLs6ZRjIj86XQ9BGqCQoSyygdg==' },
  local: {} }
```

**Comment by daffl** [comment]
Your hook wrapper isn't quite right. You are just calling the function with no context (which is why `this` is undefined. You also don't need to create a wrapper promise.

```js
exports.hookWrapper = function(options){
  const restrictToOwner = auth.restrictToOwner(options);

  return function(hook) {
    return restrictToOwner.call(this, hook);
  }
};
```

Should be all you need.

**Comment by jorgelopezs** [comment]
Is the example wrong or outdated?

**Comment by jorgelopezs** [comment]
@daffl Thanks. It works.

**Comment by daffl** [comment]
You are absolutely right, the example was wrong. Sorry about that, it is fixed now.
