### ISSUE TITLE
Hooks with mutiple entries per request

### ISSUE THREAD

**Issue by Mangatt** [feathersjs/feathers-hooks#95]
There should be definitely some change in either documentation or in way how hooks works in case of multiple entries per request (eg. create([entry, entry, ...])).

Built-in hooks works just fine, when you call `hooks.remove('id')`, it runs for every entry. However, when you want use `hook => { delete hook.data.id; }`, you accomplish nothing. Because hook.data contains array of entries.

This leaves possible security breach in a lot of applications that sanitizes hook data by hand (=not-built-in hooks).

From my point of view, there are two possible solutions:
1. **Change documentation of hooks** in way that users are aware of this problem
2. **Change behavior of hooks** so hook will run for every entry, as if they would run separately and place complete data for example to hook.multipleData

Second solution is IMO better, because it will increase security of most apps with no cost. It will break some older apps, but it will be quick fix since everything you have to do is change your hook code from hook.data to hook.multipleData (in case that your app needs to work with entire collection).

**Comment by Mangatt** [comment]
In current state of things you have to change code from

```javascript
todoService.before({
  all(hook) {
    if(!hook.params.user) {
      throw new Error('You need to be logged in');
    }
  },

  create(hook, next) {
    hook.data.createdAt = new Date();
  }
});
````

to

```javascript
todoService.before({
  all(hook) {
    if(!hook.params.user) {
      throw new Error('You need to be logged in');
    }
  },

  create(hook, next) {
    if(Array.isArray(hook.data)){
      hook.data.map( entry => {
         entry.createdAt = new Date();
      });
    }else{
      hook.data.createdAt = new Date();
    }
  }
});
````
As you can see, this is not convenient not very straightforward.

**Comment by daffl** [comment]
It is indeed more cumbersome but I'm not following why it isn't straightforward. In a hook you get the data you submit, that's it. I'm not sure if adding, testing and documenting some additional magic here would make things that much clearer.

One way to make your own hooks easier to implement would be to add a generic `create` hook before all others that always calls `create` with the individual entry so that you always get the expected behaviour:

```
app.service('myservice').before({
  create(hook) {
    if(Array.isArray(hook.data)) {
      return Promise.all(hook.data.map(entry => this.create(entry, hook.params)))
        .then(results => {
          hook.result = results;
          return hook;
        });
    }
  }
});
```

**Comment by Mangatt** [comment]
I guess this is not that straightforward because there is no mention about that in hooks chapter in docs. I guess that most people are not aware that hook.data could be array instead of single entry and that they should check that in every hook.

That way you could mess with sanitization in every average app. Even simple case with adding createdAt field from docs is screwed when someone sends array.

This might be simple (sent data = hook.data) but a bit impractical to use, because **all hooks in every app need to check  if user (which could send pretty much anything) does not sent an array**.

This is not really that simple when you think of that.

**Comment by eddyystop** [comment]
You can use `feathers-hooks-common/utils` has `getItems` and `replaceItems`. `getItems` returns the data (for a before hook) or the result (for an after hook) as an array regardless of where the items are in the hook. You can manipulate the items and then use `replaceItems`.

**Comment by eddyystop** [comment]
I'm closing this as answers have been provided and there's been no response for 5 months.

Please reopen if you think it should be open.
