### ISSUE TITLE
remove hook should check if hook.result is not null

### ISSUE THREAD

**Issue by whollacsek** [feathersjs/feathers-hooks#99]
Got error: `TypeError: Cannot read property 'toObject' of null` at https://github.com/feathersjs/feathers-hooks/blob/master/src/bundled.js#L138

**Comment by ryuken** [comment]
Did you get that because you use the hook both in before & after?

**Comment by whollacsek** [comment]
I only used it as after hook.

**Comment by daffl** [comment]
Sounds like a good change. Can probably be done by changing https://github.com/feathersjs/feathers-hooks/blob/master/src/bundled.js#L137 to `} else if(result) {`.

**Comment by kaiquewdev** [comment]
https://github.com/feathersjs/feathers-hooks/pull/101

**Comment by daffl** [comment]
v1.5.8
